CREATE DATABASE IF NOT EXISTS PWDA;
USE PWDA;

CREATE TABLE IF NOT EXISTS TB_GRUPOPERMISSAO (

PK_ID CHAR(2),
DESCRISAO TEXT,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)

);


CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
NRDOC CHAR(30),
TELEFONE VARCHAR(80),
DT_NASCIMENTO DATE NULL,
NACIONALIDADE CHAR(2),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
SEXO VARCHAR(15),
RE INT(40),
DEPARTAMENTO VARCHAR(100),
CARGO VARCHAR(100),
FK_GRUPOPERMISSAO CHAR(2),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_GRUPOPERMISSAO) REFERENCES TB_GRUPOPERMISSAO (PK_ID)

);


CREATE TABLE IF NOT EXISTS TS_LOGIN ( 

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
LOGIN VARCHAR(150),
SENHA VARCHAR(150),
FK_FUNCIONARIO BIGINT NOT NULL,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
TG_INATIVO TINYINT DEFAULT 0,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_FUNCIONARIO) REFERENCES TB_FUNCIONARIO ( PK_ID )

);

CREATE TABLE IF NOT EXISTS TB_CLIENTE (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
NRDOC CHAR(30),
SEXO VARCHAR(15),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
UF CHAR(2),
CIDADE VARCHAR(80),
CEP CHAR(9),
TELEFONE VARCHAR(80),
EMAIL VARCHAR(150),
TG_PESSOA CHAR(1),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)

);

CREATE TABLE IF NOT EXISTS TB_TIPOPRODUTO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
TIPOPROD  VARCHAR(150),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);


CREATE TABLE IF NOT EXISTS TB_PRODUTO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
PRODUTO  VARCHAR(100),
FK_TIPOPROD BIGINT NOT NULL,
QUANTIDADE NUMERIC(6),
ORIGEM VARCHAR(150),
VL_UNITARIO NUMERIC(13,2),
DESCRICAO TEXT,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_TIPOPROD) REFERENCES TB_TIPOPRODUTO ( PK_ID )

);


CREATE TABLE IF NOT EXISTS FI_VENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_CLIENTE BIGINT NOT NULL,
FK_ITEMVENDA BIGINT NOT NULL,
VL_TOTAL NUMERIC(13,2),
DT_VENDA DATE NOT NULL,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_CLIENTE) REFERENCES TB_CLIENTE (PK_ID)

);


CREATE TABLE IF NOT EXISTS FI_ITEMVENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_VENDA BIGINT NOT NULL,
FK_PRODUTO BIGINT NOT NULL,
VL_UNITARIO NUMERIC(13,2),
QUANTIDADE NUMERIC(6),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_VENDA) REFERENCES FI_VENDA ( PK_ID ),
FOREIGN KEY (FK_PRODUTO) REFERENCES TB_PRODUTO ( PK_ID )

);

SELECT * FROM TB_FUNCIONARIO;
SELECT * FROM TB_PRODUTO;
SELECT * FROM TB_TIPOPRODUTO;
SELECT * FROM TB_CLIENTE;


INSERT INTO TB_PRODUTO (PRODUTO, FK_TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO, TG_INATIVO) 
VALUES ('teste', 1, 200, 'teste', 20.0, 'merda', NOW(), 0);

INSERT INTO TB_TIPOPRODUTO (TIPOPROD, DH_INCLUSAO) 
VALUES ('Perférico', NOW());

