CREATE DATABASE IF NOT EXISTS PWDA;
USE PWDA;

CREATE TABLE IF NOT EXISTS TB_EMPRESA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
EMPRESA VARCHAR(80),
DIRETOR VARCHAR(80),
NR_CNPJ CHAR(30),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(60),
UF CHAR(2),
CEP CHAR(9),
TELEFONE VARCHAR(80),
EMAIL VARCHAR(150),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)

);


CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
NRDOC CHAR(30),
GRUPOPERMICAO CHAR(15),
TELEFONE VARCHAR(80),
DT_NASCIMENTO DATE NULL,
NACIONALIDADE CHAR(2),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
SEXO VARCHAR(15),
RE INT(40),
DEPARTAMENTO VARCHAR(100),
CARGO VARCHAR(100),
EMPRESA VARCHAR(80),
TG_PESSOA CHAR(1),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);


CREATE TABLE IF NOT EXISTS TS_LOGIN ( 

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
LOGIN VARCHAR(150),
SENHA VARCHAR(150),
PERMISSAO VARCHAR(60),
EMPRESA VARCHAR(60),
FK_FUNCIONARIO BIGINT NOT NULL,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
TG_INATIVO TINYINT DEFAULT 0,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_FUNCIONARIO) REFERENCES TB_FUNCIONARIO ( PK_ID )

);

CREATE TABLE IF NOT EXISTS TB_CLIENTE (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
NRDOC CHAR(30),
ENDERECO VARCHAR(120),
UF CHAR(2),
CIDADE VARCHAR(80),
BAIRRO VARCHAR(60),
CEP CHAR(9),
TELEFONE VARCHAR(80),
EMAIL VARCHAR(150),
TG_PESSOA CHAR(1),
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)

);


CREATE TABLE IF NOT EXISTS TB_PRODUTO (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
PRODUTO  VARCHAR(100),
TIPOPROD VARCHAR(60),
QUANTIDADE NUMERIC(6),
ORIGEM VARCHAR(150),
VL_UNITARIO NUMERIC(13,2),
DESCRICAO TEXT,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID)
);


CREATE TABLE IF NOT EXISTS FI_VENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_CAIXA BIGINT NOT NULL,
FK_CLIENTE BIGINT NOT NULL,
FK_EMPRESA BIGINT NOT NULL,
VL_TOTAL NUMERIC(13,2),
QUANTIDADE NUMERIC(6),
DT_VENDA DATE NOT NULL,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_CAIXA) REFERENCES TS_LOGIN (PK_ID),
FOREIGN KEY (FK_CLIENTE) REFERENCES TB_CLIENTE (PK_ID),
FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA (PK_ID)

);


CREATE TABLE IF NOT EXISTS FI_ITEMVENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_VENDA BIGINT NOT NULL,
FK_PRODUTO BIGINT NOT NULL,
TG_INATIVO TINYINT DEFAULT 0,
DH_INCLUSAO DATETIME,
DH_ALTERACAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_VENDA) REFERENCES FI_VENDA ( PK_ID ),
FOREIGN KEY (FK_PRODUTO) REFERENCES TB_PRODUTO ( PK_ID )

);


INSERT INTO TB_FUNCIONARIO (NOME, NRDOC, TELEFONE, DT_NASCIMENTO, NACIONALIDADE, ENDERECO, BAIRRO,CIDADE, UF, CEP, EMAIL, SEXO, RE, DEPARTAMENTO, CARGO, DH_INCLUSAO, TG_INATIVO)
VALUES ('DIRETOR', '0000000000000', '0000000000', NOW(), 'BR', 'ENDERECO 1', 'BAIRRO 1', 'CIDADE 1', 'SP', '000000', 'DIRETOR@HOTMAIL.COM', 'M', '01', 'DIRETORIA', 'DIRETOR', NOW(), 0);
INSERT INTO TS_LOGIN (LOGIN, SENHA, PERMISSAO, EMPRESA, FK_FUNCIONARIO, DH_INCLUSAO,TG_INATIVO)
VALUES ('DIRETOR', '$2a$10$Ky/EnXKD9GPjaPpdHwsxauVGITi54Iuqd6xRSivoYaa.tKcfIUMIW', 'DIRETOR', 'PWDA SÃO PAULO', 1, NOW(), 0);


INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('TECLADO', 'PERIFÉRICO', 200, 'USA', 60.0, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('MOUSE', 'PERIFÉRICO', 200, 'USA', 79.5, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('CARREGADOR', 'PERIFÉRICO', 200, 'USA', 249.99, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('MONITOR', 'IPS', 200, 'USA', 700, 'BRANCO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('PENDRIVE 64GB', 'PERIFÉRICO', 200, 'USA', 159.99, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('HD EXTERNO', 'PERIFÉRICO', 200, 'USA', 300, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('PROCESSADOR I7', 'HARDWARE', 200, 'USA', 900, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('MODEM', 'HARDWARE', 200, 'USA', 150, 'CINZA', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('SSD 250GB', 'HARDWARE', 200, 'USA', 440, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('HD 1TB', 'HARDWARE', 200, 'USA', 300, 'CINZA', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('NOTEBOOK', 'PORTATIL', 200, 'USA', 2500.00, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('DESKTOP', 'MESA', 200, 'USA', 3500.00, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('MEMÓRIA RAM 16GB', 'HARDWARE', 200, 'USA', 300, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('PLACA MÃE', 'HARDWARE', 200, 'USA', 500, 'PRETO', NOW());
INSERT INTO TB_PRODUTO (PRODUTO, TIPOPROD, QUANTIDADE, ORIGEM, VL_UNITARIO, DESCRICAO, DH_INCLUSAO) 
VALUES ('FONTE 500W', 'HARDWARE', 200, 'USA', 450, 'PRETO', NOW());



INSERT INTO TB_EMPRESA (EMPRESA, DIRETOR, NR_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE, EMAIL, DH_INCLUSAO)
VALUES ('São Paulo', 'Wesley', 45672951000145, 'Rua ali nº 66', 'Jd. Campo Limpo', 'São Paulo','SP', '02364580', '2244-3355', 'pwdasampa@pwda.com', NOW());
INSERT INTO TB_EMPRESA (EMPRESA, DIRETOR, NR_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE, EMAIL, DH_INCLUSAO)
VALUES ('Campina Grande', 'Darlan', 68314310000114, 'Rua ali nº 66', 'Jd. Campo Limpo', 'Campina Grande','PB', '02364580', '2244-3355', 'pwdacampina@pwda.com', NOW());
INSERT INTO TB_EMPRESA (EMPRESA, DIRETOR, NR_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE, EMAIL, DH_INCLUSAO)
VALUES ('Brasília', 'Alison', 74791701000122, 'Rua ali nº 66', 'Jd. Campo Limpo', 'Brasília','DF', '02364580', '2244-3355', 'pwdacampina@pwda.com', NOW());
INSERT INTO TB_EMPRESA (EMPRESA, DIRETOR, NR_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE, EMAIL, DH_INCLUSAO)
VALUES ('Joinville', 'Marina', 13363198000110, 'Rua ali nº 66', 'Jd. Campo Limpo', 'Joinville','SC', '02364580', '2244-3355', 'pwdabrasilia@pwda.com', NOW());



INSERT INTO TB_CLIENTE (NOME, NRDOC, ENDERECO, UF, CIDADE, BAIRRO, CEP, TELEFONE, EMAIL, TG_PESSOA, DH_INCLUSAO)
VALUES ('Pedro', '44044838801', 'Rua teste, nº0', 'SP', 'São Paulo', 'Jd. fontalis', '02364-580', '3344-0099', 'pedro@teste.com', 'F', NOW());
